on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    steps:
      - uses: actions/checkout@v2 
      - run: make check
  build_tests:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: cd project
    - run: mkdir build
    - run: cmake . 
    - run: cmake ..
   
    - run: make 
   
    - run: valgrind --tool=memcheck --leak-check=yes ./tests/test_product
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: products.out
 
