on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    steps:
      - uses: actions/checkout@v2 
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: cd project
    - run: mkdir build
    - run: cd build
    - run: cmake ..
    - run: make 
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: products.out
  test:
    runs-on: ubuntu-latest
    container: leshiy1295/gcc_linters
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: cd project
      - run: cd build
      - run: apt install valgrind
      - run: valgrind --tool=memcheck --leak-check=yes ./tests/test_product
